version: "3"
services:

  api:
    build: ./api
    container_name: api_c
    # ports:
    #   - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - mern-app

  app:
    build: ./app
    container_name: app_c
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - anonymous-vol:/app/node_modules
    stdin_open: true
    tty: true
    networks:
      - mern-app

volumes:
  anonymous-vol:
    driver: local

networks:
  mern-app:
    driver: bridge